name: iOS Build

on:
  pull_request:
    branches: [ develop ]  # Chỉ chạy khi có PR vào nhánh develop

jobs:
  build:
    name: Build iOS Project
    runs-on: macos-latest   # Chạy trên máy ảo macOS

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2   # Lấy source code từ PR

    - name: Set up Xcode
      run: sudo xcode-select -s /Applications/Xcode.app
      # Có thể không cần nếu runner đã sẵn sàng

    - name: Build project with xcodebuild
      run: |
        xcodebuild clean build \
        -project SimpleAppSwiftUI.xcodeproj \
        -scheme SimpleAppSwiftUI \
        -destination 'platform=iOS Simulator,name=iPhone 14' \

